"""Generated data-only size debt manifest. Regenerate with scripts/regenerate_size_ratchet.py."""

BASELINE_SOURCE_SHA = "77d6827b7a72a632899bb6cc64a7e759aabcfaa6"

GIANT_PATHS = (
    "devtools/benchmarks/osworld/run_cu_bridge_agent.py",
    "devtools/benchmarks/osworld/run_step_agent.py",
    "ouroboros/tools/git.py",
    "server.py",
    "skills/unix_computer_use/plugin.py",
    "supervisor/workers.py",
    "tests/test_claudexor_owned_daemon.py",
    "tests/test_delivery_forced_finalization.py",
    "tests/test_devtools_benchmarks.py",
    "tests/test_extensions_api.py",
    "tests/test_model_slot_role_model.py",
    "tests/test_osworld_cu_bridge.py",
    "tests/test_preflight_runner.py",
    "tests/test_promote_chat_flow.py",
    "tests/test_runtime_mode_core.py",
    "tests/test_runtime_mode_elevation.py",
    "tests/test_scope_review.py",
    "tests/test_skill_exec.py",
    "tests/test_skill_loader.py",
    "tests/test_task_status_flow.py",
    "tests/test_ui_smoke_playwright.py",
    "web/modules/chat.js",
    "web/tests/harness_accounts.test.js",
)

FUNCTION_DEBT = (
    ("ouroboros/agent_startup_checks.py", "verify_restart"),
    ("supervisor/events_schedule_task.py", "_handle_schedule_task"),
)

BAND_BASELINE_PATHS = (
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py",
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py",
    "devtools/benchmarks/terminal_bench/run_tb.py",
    "launcher.py",
    "ouroboros/agent_startup_checks.py",
    "ouroboros/claudexor_runtime.py",
    "ouroboros/context.py",
    "ouroboros/extension_process_runner.py",
    "ouroboros/gateway/contracts.py",
    "ouroboros/gateway/extensions.py",
    "ouroboros/gateway/history.py",
    "ouroboros/gateway/tasks.py",
    "ouroboros/launcher_bootstrap.py",
    "ouroboros/loop_llm_call.py",
    "ouroboros/loop_tool_execution.py",
    "ouroboros/outcomes.py",
    "ouroboros/platform_layer.py",
    "ouroboros/preflight_runner.py",
    "ouroboros/protected_artifacts.py",
    "ouroboros/skill_loader.py",
    "ouroboros/skill_review_runner.py",
    "ouroboros/subagents.py",
    "ouroboros/task_results.py",
    "ouroboros/task_status.py",
    "ouroboros/tools/browser.py",
    "ouroboros/tools/shell_guards.py",
    "ouroboros/tools/skill_exec.py",
    "ouroboros/utils.py",
    "ouroboros/workspace_executor.py",
    "scripts/run_external_review.py",
    "skills/telegram/plugin.py",
    "skills/telegram/scripts/companion.py",
    "skills/telegram/scripts/sidecar.py",
    "supervisor/evolution_lifecycle.py",
    "supervisor/terminal_delivery.py",
    "tests/test_acting_subagents.py",
    "tests/test_advisory_observability.py",
    "tests/test_build_scripts.py",
    "tests/test_claude_code_gateway.py",
    "tests/test_commit_gate.py",
    "tests/test_contracts.py",
    "tests/test_evolution_redesign.py",
    "tests/test_observability_outcomes_v2.py",
    "tests/test_onboarding_complete_endpoint.py",
    "tests/test_onboarding_wizard.py",
    "tests/test_packaged_runtime_and_lifecycle.py",
    "tests/test_review_fidelity.py",
    "tests/test_review_verification_v6544.py",
    "tests/test_safety_policy.py",
    "tests/test_swe_pro_e1v2.py",
    "tests/test_telegram_miniapp_lifecycle.py",
    "tests/test_tool_api_v2_public_surface.py",
    "tests/test_usage_accounting.py",
    "tests/test_v647_megacommit.py",
    "tests/test_v6730_origin_invariant.py",
    "tests/test_v678_receipt_reconciliation.py",
    "web/modules/harness_accounts.js",
    "web/modules/harness_login_cards.js",
    "web/modules/log_events.js",
    "web/modules/onboarding_wizard.js",
    "web/modules/settings.js",
    "web/modules/widgets.js",
)

BAND_PATHS = {
    "devtools/benchmarks/cybergym/cybergym_adapter.py": "Stateful campaign layer after the protocol split (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/cybergym_docker.py": "Docker runtime layer of the executor split: one container-machinery seam.",
    "devtools/benchmarks/cybergym/cybergym_executor.py": "Executor assembly after docker/lifecycle/wire splits (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/cybergym_lifecycle.py": "Run/settle lifecycle layer of the executor split: one accounting seam.",
    "devtools/benchmarks/cybergym/cybergym_protocol.py": "Stateless protocol layer of the adapter split: constants, validators, provenance.",
    "devtools/benchmarks/cybergym/cybergym_sidecar.py": "Sidecar attestation core after the observations split (ratchet heal); shrink next touch.",
    "devtools/benchmarks/cybergym/run_cybergym.py": "CyberGym launcher is one submit-shaped entry point (drift heal); split when a second arm lands.",
    "devtools/benchmarks/swe_bench_pro/e1v2/run_pro.py": None,
    "devtools/benchmarks/terminal_bench/harbor_installed_agent.py": None,
    "devtools/benchmarks/terminal_bench/run_tb.py": None,
    "ouroboros/agent.py": "Subagent message identity now lives in a shared helper; keep agent.py below the giant-file threshold rather than re-expanding it.",
    "ouroboros/agent_startup_checks.py": "Re-entered the band from the 1501-1600 zone by the CPL4-C9 removal of the dead crash-report reader; the re-entry is the reduction's artifact, not growth.",
    "ouroboros/agent_task_pipeline.py": "Shrank INTO the band from 1599 lines: the post-task synthesis family moved byte-preserving into ouroboros/post_task_synthesis.py (D01 lane); no new content was added.",
    "ouroboros/artifacts.py": "Exact task-source persistence and repository-diff materialization now share the actor-readable artifact seam for acceptance evidence.",
    "ouroboros/cancel_intents.py": "Entered the band from 929 lines: reciprocal timeout-retry lineage validation and physical-leaf/logical-root aliasing stay with the durable cancel-intent mutation authority so Stop-now hardens the same request across retry races.",
    "ouroboros/capability_evidence.py": "Grew INTO the band by the #284 fix: a fresh exact-model density witness may honestly undercut the cold floor \u2014 evidence logic belongs beside the witness store it reads.",
    "ouroboros/consciousness.py": "Durable Background Consciousness observation inbox and bounded truthful replay",
    "ouroboros/context.py": "Entered the band from the 1501-1600 zone (1590 lines) by the v7 D03 extraction of the runtime-section fact builders into ouroboros/context_runtime_facts.py; shrink-only residue of the split, not new growth.",
    "ouroboros/delegate_custody.py": "D07 DEL1 split brought the custody monolith DOWN from the 1600 hard cap into the band (1600->1305); reconcile family extracted to delegate_custody_reconcile.py, shrink-only direction",
    "ouroboros/extension_process_runner.py": None,
    "ouroboros/gateway/control.py": "Entered the band from 966 lines: the update-flow redesign added the shared stash-first prologue (_stash_local_work_fenced/_unwind_stashed_update) and the review-wave affordability floor to the update apply orchestration (update-flow-redesign sprint, Q9/Q10 owner decisions).",
    "ouroboros/gateway/settings.py": "Retiring persistent auto-Low removed the former giant debt; the remaining owner and reviewer settings endpoints stay centralized while tracked in the shrinking band.",
    "ouroboros/loop_acceptance_review.py": "F6 upstream sync: the A-material acceptance family (paid identity, free replay, identical-refusal terminal, dialogue history) folded into the campaign review leaf per the sync principle (upstream leaf acceptance_dialogue.py retired)",
    "ouroboros/loop_delivery.py": "F6 upstream sync: the delivery-protocol upstream deltas (hold-control literals, trailing-object/fence-aware protocol parsers) folded into the campaign delivery leaf (upstream leaf delivery_protocol.py retired)",
    "ouroboros/loop_forced_finalization.py": "Forced-finalization rail of the v7 L-B loop split: one cohesive owner for the forced/orphan/absorption path, moved byte-preserving from loop.py (D01 lane).",
    "ouroboros/loop_tool_execution.py": None,
    "ouroboros/marketplace/ouroboroshub.py": "Entered the band from 373 lines: the hubflow sprint added the adopt transaction (eligibility prelude, CAS re-verification, move-aside + state-quintet snapshot, verified rollback with per-step error collection, retention finalize) beside the existing install/update flows (hubflow sprint, adopt-in-ouroboroshub owner decision D4).",
    "ouroboros/mcp_client.py": "F3.1 typed-organ producer cutover (D05 entry 7b): the MCP transport keeps the SDK-owned error bit as a typed ToolResult and reports provider-slug collisions as evidence; grew into the band from 984 lines, shrink-only otherwise.",
    "ouroboros/observability.py": "Entered the band from 820 lines: child task copy-back now promotes only promised observability CAS manifests/blobs and task-owned source handles into canonical storage before headless GC, with typed unavailable gaps and retry metadata.",
    "ouroboros/platform_layer.py": "Shrank INTO the band: the retired Claude-SDK runtime probes (resolve_claude_runtime, ClaudeRuntimeState) were deleted with the transport (owner-approved Q4 retirement); no new content was added.",
    "ouroboros/preflight_runner.py": None,
    "ouroboros/projects_registry.py": "Entered the band from 999 lines: the stuck-Working liveness sprint homed the project-thread membership lens (mtime-cached) and its broadcast-choke marker here \u2014 registry semantics belong to the registry, not to message_bus.",
    "ouroboros/protected_artifacts.py": None,
    "ouroboros/review.py": "Entered the band from 952 lines: re-anchoring the size ratchet on the official line added the candidate and pairwise base-vs-tip transition validators (validate_size_ratchet_candidate/validate_size_ratchet_transition_against_base) with merge-aware previous-manifest resolution, replacing the retired first-parent history audit (update-flow-redesign sprint, Q7-C/Q18-A/Q19-A owner decisions).",
    "ouroboros/review_custody.py": "Review custody now owns the shared typed retry-rail history and frozen actor reconstruction so physical outcomes cannot be lost between the substrate and reconciliation.",
    "ouroboros/review_execution.py": "Verdict extraction and the native tool-round executor moved to their own modules (generic reviewer-actor sprint); the transport seam re-enters the band smaller and more cohesive.",
    "ouroboros/reviewer_slot_config.py": "Absorbed the reviewer_slots() builder from review_substrate (altitude) and configured-subagent row resolution for the generic reviewer-actor bridge.",
    "ouroboros/safety.py": "Entered the band from 954 lines with the safety-supervisor rate-limit fix: ONE shared model-call helper now serves both the primary and repair safety calls (it already deletes the duplicated call block), recognising a provider rate limit in BOTH wire shapes, taking one bounded deadline-capped backoff plus one retry, then blocking that one call with the typed non-verdict SAFETY_UNAVAILABLE outcome plus a durable audit row (a short storm latch answers further checks in the window without provider calls); the bounded newest-first conversation budget is the second half.",
    "ouroboros/skill_review_runner.py": None,
    "ouroboros/subagent_runtime.py": "Configured-retry refusals mirrored typed (triad 2026-08-30) push the module just over 1000; no new subsystem, same seam.",
    "ouroboros/subagent_worktrees.py": "Owner-sanctioned strict-registry delta (v7 rows 1083-1092, fork F-1=A) grew the module 1000->1082: typed refusal of a malformed registry instead of silent collapse-to-empty; shrink-only direction",
    "ouroboros/subagents.py": "D07 split brought the dispatch monolith DOWN from 1593 into the band (->1370); route-health family extracted to subagent_route_health.py, shrink-only direction",
    "ouroboros/task_status.py": None,
    "ouroboros/tools/browser.py": None,
    "ouroboros/tools/claude_advisory_review.py": "F2.3b advisory re-derive: the 2279-line GIANT parent re-enters the band at 1434 after the preflight_review_prompt/preflight_review_run split (admission policy, native episode, size gates and the tool entries stay with the facade)",
    "ouroboros/tools/commit_gate.py": "Grew INTO the band by the review-wave fix binding the actor reference (delivery class) into the commit review contract fingerprint \u2014 same-module contract identity, splitting it would separate the fingerprint from its gate.",
    "ouroboros/tools/core.py": "D05 ledger split (rows 311-349): read/list and owner-chat delivery spans moved to core_file_tools/core_artifacts; facade re-enters the band from above (2283 -> 1373) and shrinks further when the residual catalog split lands",
    "ouroboros/tools/delegate.py": "D07 finisher DEL1 split brought the nanny-verb monolith DOWN from the 1600 hard cap into the band (1600->1263); terminal-evidence family extracted to tools/delegate_terminal_evidence.py, shrink-only direction",
    "ouroboros/tools/plan_review_runtime.py": "Entered the band from 986 lines: timeout custody synthesis joined the existing plan-review runtime owner while preserving profile-continuity disclosures and typed health facts during target integration.",
    "ouroboros/tools/registry_core.py": "F3.1 typed-organ re-split (D04 rows 156/167/170/171/174/175): the tip ToolRegistry class body re-homed whole from the protected registry facade; the guard/dispatch surface already left for its sibling leaves, and the class shrinks further only with the ABI-8 post-release handler conversion.",
    "ouroboros/tools/review.py": "D06 F2.3a re-entry by extraction: the multi-model fan-out moved to review_multi_model.py (1550->1269); the remaining single-owner review cycle machinery lands in the 1001-1500 band with headroom",
    "ouroboros/tools/review_context_atlas.py": "Grew INTO the band by the #284 pack-arithmetic fixes: measured render charged at admission, exact per-row costs, target capped at the hard rail, honest eviction diagnostics \u2014 all in the module that owns the arithmetic.",
    "ouroboros/tools/skill_exec.py": None,
    "ouroboros/tools/skill_publish.py": "Entered the band from 952 lines: publish now writes the OuroborosHub publication receipt at pr_opened through the shared locked-update seam and maps the receipt from the validated serialized form (hubflow sprint, receipt-as-only-stored-fact design).",
    "ouroboros/usage_accounting.py": "Entered the band from the 1501-1600 zone (1600 lines) by the v7 L-C2 extraction of the one-time legacy usage import into ouroboros/usage_legacy_import.py; shrink-only residue of the split, not new growth.",
    "ouroboros/workspace_executor.py": None,
    "scripts/v7next_transplant.py": "F0 phase-review CRITICAL hardening: whole-leaf runtime invariants (handle existence/shape, declared/preamble disjointness, unread-declared) added to the byte-proof verifier; campaign tool retires with F6, not a runtime module",
    "skills/telegram/plugin.py": None,
    "skills/telegram/scripts/companion.py": None,
    "skills/telegram/scripts/sidecar.py": None,
    "supervisor/evolution_lifecycle.py": None,
    "supervisor/message_bus.py": "push_log gained the A2A frame suppression and explicit-addressing contract comments in the live log routing fix (fix/main-chat-leak sprint); the module sat at exactly 1000 lines before it",
    "supervisor/queue_transitions.py": "F2.2 cancel/custody organ: the owner-stop campaign closure (_close_campaign_after_owner_stop, reference row 970) moved in from the hot events monolith to live beside stop_evolution_tasks - one honesty rule, one owner; 1016 lines, shrink-only from here",
    "supervisor/terminal_delivery.py": None,
    "supervisor/update_merge.py": "Entered the band from above (1593 lines) by extraction: the F2.4 update-engine re-split moved the planner, the clean-plan commit builder and the live materializer \u2014 the carrier engine's three insertion points \u2014 into supervisor/update_merge_plan.py (D34 return, owner answers 5.12-5.14=A); shrink-only.",
    "tests/system_e2e/harness.py": "system_e2e harness: waves 3a+3b grew the one scenario-suite machinery module into the band \u2014 skill-review stub branch, review-organ verdict scripting (ReviewScript), plan-review/native-episode classification markers, the advisory reviewer-slot row and the S11-S17 manifest rows; split when the next wave lands new actors.",
    "tests/test_acting_subagents.py": None,
    "tests/test_advisory_observability.py": None,
    "tests/test_build_scripts.py": None,
    "tests/test_commit_gate.py": None,
    "tests/test_cybergym_protocol.py": "CyberGym protocol suite arrived in one piece with the benchmark (drift heal); split when the next protocol family lands.",
    "tests/test_delegate_answer.py": "Entered the band by the #204 escalation-route pins (walk-up, schema and expiry-note source pins) on top of the phase-B interaction suite; one coherent delegated-question surface, split only when a natural seam appears",
    "tests/test_delegated_skill_payload.py": "Sol scope-review fix batch: P1 trust probes (forged index, symlinked git metadata), P2 golden-E2E review close and schema/docs pins joined the existing R1+gate-fix payload suite.",
    "tests/test_evolution_redesign.py": None,
    "tests/test_external_review_script.py": "F2.3b D31 port: the reference trusted-base pin suite (probe-backed handoff/forwarding/in-place/dirty/e2e pins plus the new no-list-membership and wrapperless fail-closed pins) joins the existing contributor-lane suite",
    "tests/test_external_workspace_access.py": "Deliverables custody matrix covers nested roots, executor aliases, Presence ceilings, and direct shell target semantics.",
    "tests/test_loop_transport_wait.py": "Contract suite for the transport-wait episode: classification, custody, round-level wait, terminals, and the final-review regression pins live together as one coherent surface.",
    "tests/test_managed_review_subject.py": "Lane L-review contract suite: the managed resolution-delta subject (gate/advisory surfaces, M0 fallback), Q25-A admission, Q28-A yield outcomes and enforcement-honest advisory texts grew past 1000 across the adversarial fix round; one subject, one suite.",
    "tests/test_nested_rights_depth.py": "Nested delegation depth authority regression coverage",
    "tests/test_observability_outcomes_v2.py": None,
    "tests/test_onboarding_complete_endpoint.py": None,
    "tests/test_onboarding_wizard.py": None,
    "tests/test_owner_stop_s3.py": "Entered the band from 821 lines: the S3 contract suite now covers retry-root aliasing, graceful-to-immediate hardening, stale-control drain races, hard deadline preservation, descendant settlement failure, and late resweep exactly-once root finalization.",
    "tests/test_packaged_runtime_and_lifecycle.py": None,
    "tests/test_provider_failure_reporting.py": "Entered the band from 938 lines: the provider-failure honesty rework added the retry-wall marker suites (entry-clear, all-retryable stamp, empty-response provider-failing gate, no-repay rail) beside the cost-validation suites (bool/NaN/inf/negative/huge-int at both boundaries) - one file per failure-reporting surface.",
    "tests/test_repo_health_smoke.py": "size-ratchet redesign: merge-aware previous, pairwise base-vs-tip, candidate-mode generator contract tests",
    "tests/test_review_agent_session_route.py": "D06 F2.3a re-entry by extraction: the session-route giant (3399) split into three sibling suites + shared fixtures; this remainder keeps the typed-verdict/route themes at 1218 with headroom",
    "tests/test_review_fidelity.py": None,
    "tests/test_review_verification_v6544.py": None,
    "tests/test_safety_policy.py": None,
    "tests/test_skill_review_runner.py": "Skill lifecycle/review terminal-state regression coverage stays one focused suite below the 1500-line band cap.",
    "tests/test_swe_pro_e1v2.py": None,
    "tests/test_telegram_miniapp_lifecycle.py": None,
    "tests/test_terminal_durability_v664.py": "Entered the band from 974 lines: terminal durability coverage now pins retry-admission failure custody so an unpersisted terminal row cannot publish task_done or lose the retry marker.",
    "tests/test_timeout_policy.py": "Adaptive timeout and custody regression suite covers raw-deadline admission, explicit finalization reserve, transport bounds, and late-result reconciliation.",
    "tests/test_tool_result.py": "F3.1 typed-organ pins carried with the D02 organ (D04 entry 9): the closed code table, the one legacy-text adapter, the publish/sidecar seam and the meta-boundary contracts pin one organ in one suite; sibling suites (meta_boundaries, t46, classification differential) already hold the spill-over families.",
    "tests/test_usage_accounting.py": None,
    "tests/test_usage_compaction.py": "Entered the band from 874 lines: the round-3 adversarial pins (lock ownership and heartbeat abort, retry durability of the archive chain, the live-epoch archive anchor, the segment-cache re-hash window, archive symlink bounds) belong beside the monetary-compaction invariants they defend, as one suite.",
    "tests/test_v6730_origin_invariant.py": None,
    "tests/test_v678_receipt_reconciliation.py": None,
    "web/modules/api_types.js": "The shared browser contract module now includes issue 265 publication-preflight types alongside the target settings and subagent contracts.",
    "web/modules/harness_accounts.js": None,
    "web/modules/log_events.js": None,
    "web/modules/onboarding_wizard.js": "Shrank INTO the band: the Claude Runtime onboarding card and its /api/claude-code/* polling were deleted with the retired transport (owner-approved Q4); no new content was added.",
    "web/modules/review_presentation.js": "Review Checkpoint read-side grouping, lifecycle/verdict separation, and keyed disclosure reconciliation remain one pure adapter below the 1500-line band cap.",
    "web/modules/reviewer_slots.js": "Owner-approved 5A editor: per-row Direct model / Configured subagent source picker with read-only derived disclosure replaces the legacy Claude-SDK advisory input in the same module that owns reviewer-row editing.",
    "web/modules/settings.js": None,
    "web/modules/widgets.js": None,
    "web/tests/harness_login_cards.test.js": "Login-card suite grew past 1000 lines with the name-the-account face cases (agy pickup, issue #232); split when the next face lands.",
    "web/tests/review_presentation.test.js": "Review Checkpoint lifecycle and verdict reconciliation remain covered by one focused presentation suite.",
}

BYTE_BASELINE_DEBT = {
    "ouroboros/llm.py": 205432,
    "ouroboros/loop.py": 335600,
    "supervisor/events.py": 205328,
    "tests/test_delegated_subagent_transport.py": 320627,
    "tests/test_devtools_benchmarks.py": 328786,
    "web/modules/chat.js": 234467,
}

BYTE_DEBT = {
    "tests/test_devtools_benchmarks.py": 327883,
    "web/modules/chat.js": 210935,
}
